version: '3'

services:
    db:
        image: postgres
        restart: always
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres

    web:
        build: .
        volumes:
            - .:/usr/src/app
        ports:
            - "8000:8000"
        environment:
            - DB_NAME=postgres
            - DB_USER=postgres
            - DB_PASSWORD=postgres
            - DB_HOST=db
            - DB_PORT=5432